# Generated by Django 3.2 on 2021-10-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netauto', '0007_detector'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_id', models.CharField(blank=True, max_length=256, verbose_name='Hash ID')),
                ('time', models.DateTimeField(null=True, verbose_name='Time')),
                ('detection_time', models.CharField(max_length=200, null=True, verbose_name='Detection time')),
                ('source_ip', models.CharField(max_length=200, verbose_name='Source IP address')),
                ('dst_ip', models.CharField(default='any', max_length=200, verbose_name='Destination IP address')),
                ('dst_port', models.CharField(blank=True, default=None, max_length=200, verbose_name='Destination port')),
                ('conn_protocol', models.CharField(blank=True, max_length=200, verbose_name='Protocol')),
                ('conn_flag', models.CharField(blank=True, max_length=200, verbose_name='Connection flag')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExecTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_name', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='auto_mitigate',
            field=models.BooleanField(default=False, verbose_name='Auto-mitigate'),
        ),
        migrations.AddField(
            model_name='device',
            name='default_acl_id',
            field=models.CharField(default='nil', max_length=128, verbose_name='Default ACL ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=200, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.CharField(max_length=200, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(max_length=200, verbose_name='Username'),
        ),
    ]
